[package]
name = "guff_css"
version = "0.3.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.72"
description = "A simple SASS/SCSS compiler and CSS parser/minifier."
repository = "https://github.com/Blobfolio/guff"
readme = "README.md"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[dependencies]
dactyl = "0.7.*"
oxford_join = "0.2.*"
trimothy = "0.2.*"

[dependencies.argyle]
version = "0.7.2"
optional = true

[dependencies.grass]
version = "=0.13.3"
default-features = false

[dependencies.lightningcss]
version = "=1.0.0-alpha.56"
default-features = false
features = [ "grid" ]

[build-dependencies]
dactyl = "0.7.*"

[build-dependencies.minreq]
version = "2.11.*"
default-features = false
features = ["https"]

[build-dependencies.serde]
version = "1.0.*"
features = [ "derive" ]

[build-dependencies.serde_json]
version = "1.0.*"

[features]
default = []

# Used by the CLI binary.
bin = [ "argyle" ]
