.TH "GUFF" "1" "March 2022" "Guff v0.0.7" "User Commands"
.SH NAME
Guff \- Manual page for guff v0.0.7.
.SH DESCRIPTION
An SCSS parser and CSS minifier rolled into one.
.SS USAGE:
.TP
guff [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-b\fR, \fB\-\-browsers\fR <LIST>
Comma\-separated list of browser compatibility requirements, like 'last 2 versions, not dead, firefox 97'. Usage\-based rules are unsupported.
.TP
\fB\-i\fR, \fB\-\-input\fR <FILE>
The path to an SCSS or CSS source file.
.TP
\fB\-o\fR, \fB\-\-output\fR <FILE>
The path to save the minified output to. If omitted, the result will be printed to STDOUT instead.
