.TH "GUFF" "1" "February 2025" "guff v0.6.1" "User Commands"
.SH NAME
GUFF \- Manual page for guff v0.6.1.
.SH DESCRIPTION
A simple SASS/SCSS compiler and CSS parser/minifier.
.SS USAGE:
.TP
guff [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-e\fR, \fB\-\-expanded\fR
Do not minify CSS.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-b\fR, \fB\-\-browsers\fR <VER>
A comma\-separated list of specific browser/version pairs to target for CSS compatibility, like 'firefox 90, ie 11'.
.TP
\fB\-i\fR, \fB\-\-input\fR <FILE>
The path to an SCSS or CSS source file.
.TP
\fB\-o\fR, \fB\-\-output\fR <FILE>
The path to save the minified output to. If omitted, the result will be printed to STDOUT instead.
