name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - aarch64-apple-darwin
        include:
        - target: x86_64-unknown-linux-gnu
          os:     ubuntu-latest
        - target: aarch64-apple-darwin
          os:     macos-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        components: clippy

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - name: Build
      run: |
        cargo build --bin guff --all-features --target ${{ matrix.target }}
        cargo build --bin guff --release --all-features --target ${{ matrix.target }}

    - name: Clippy
      run: |
        cargo clippy --all-features --target ${{ matrix.target }}

    - name: Tests
      run: |
        cargo test --all-features --target ${{ matrix.target }}
        cargo test --release --all-features --target ${{ matrix.target }}

    - name: Tests (Library Only)
      run: |
        cargo test -p guff_css --target ${{ matrix.target }}
        cargo test --release -p guff_css --target ${{ matrix.target }}
